name: .NET

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore nugets
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Run tests
      run: dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx"
    - name: Upload tests results
      uses: actions/upload-artifact@v3
      with:
        name: NUnit-Test-Results
        path: '**/TestResults/test-results.trx'
