name: .NET

on: 
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore nugets
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
